services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data_fake:/var/lib/neo4j/import/data_fake
    environment:
      NEO4J_AUTH: neo4j/cH4ng3M3
      NEO4J_PLUGINS: '["graph-data-science"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

  importer:
    build: .
    depends_on:
      - neo4j
      - qdrant
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: cH4ng3M3
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_COLLECTION: neo4j_qdrant_cache # Optional but recommended

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # gRPC port
      - "6334:6334" # HTTP port
    volumes:
      - ./qdrant_data:/qdrant/storage